spring:
  application:
    name: eureka-server-2th
  security:
    user:
      name: ecin520
      password: guowei00a

server:
  port: 4002

eureka:
  instance:
    hostname: eureka-2th.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://ecin520:guowei00a@www.eureka-1th.com:4001/eureka/

info:
  app.name: e-mall
  designer.name: Ecin520
  designer.school: JXNU
